config/routes.rb
Rails.application.routes.draw do

  resources :destinations
  resources :mice

  get 'welcome/index'

  get 'mice/contact'

  get 'contact' => 'welcome#contact'

  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  geocoded_by :address
  after_validation :geocode

#reverse_geocoded_by :latitude, :longitude
#after_validation :reverse_geocode
end

app/models/mouse.rb
class Mouse < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
 def index
    # @destinations = Destination.all
    if params[:country] == nil
      @destinations = Destination.all
      elsif
      @destinations = Destination.where(country: params[:country].titleize)
    elsif
      @destinations = Destination.where(country: params[:country].upcase)
    end

    # unordered
    # @my_countries = Destination.select(:country).distinct

    # alphabetical
    @my_countries = Destination.select(:country).order(:country).distinct

  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :description, :population, :avatar, :latitude, :longitude, :address)
    end
end

app/controllers/mice_controller.rb
class MiceController < ApplicationController
  before_action :set_mouse, only: [:show, :edit, :update, :destroy]

  # GET /mice
  # GET /mice.json
  def index
    @mice = Mouse.all
  end

  # GET /mice/1
  # GET /mice/1.json
  def show
  end

  def contact
  end

  # GET /mice/new
  def new
    @mouse = Mouse.new
  end

  # GET /mice/1/edit
  def edit
  end

  # POST /mice
  # POST /mice.json
  def create
    @mouse = Mouse.new(mouse_params)

    respond_to do |format|
      if @mouse.save
        format.html { redirect_to @mouse, notice: 'Mouse was successfully created.' }
        format.json { render :show, status: :created, location: @mouse }
      else
        format.html { render :new }
        format.json { render json: @mouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mice/1
  # PATCH/PUT /mice/1.json
  def update
    respond_to do |format|
      if @mouse.update(mouse_params)
        format.html { redirect_to @mouse, notice: 'Mouse was successfully updated.' }
        format.json { render :show, status: :ok, location: @mouse }
      else
        format.html { render :edit }
        format.json { render json: @mouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mice/1
  # DELETE /mice/1.json
  def destroy
    @mouse.destroy
    respond_to do |format|
      format.html { redirect_to mice_url, notice: 'Mouse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mouse
      @mouse = Mouse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mouse_params
      params.require(:mouse).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @homeland = 'Puerto Rico'
    @countries = ['Chile','Bolivia','Croatia']
    @travel_pics = ['chile.jpg', 'bolivia.jpg', 'croatia.jpg']

     @united_states = {"capital city" => "Washington, DC",
                     "favorite city" => "New York, NY",
                     "favorite state" => "Texas",
                     "flag colors" => ["red", "white", "blue"]}
  end

  def about
    @color = params[:color]
    @size = params[:size].to_i
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/examp_helper.rb
module ExampHelper
end

app/helpers/mice_helper.rb
module MiceHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, placeholder: "City", class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :country %><br>
    <%= f.text_field :country, class: "form-control" %>
  </div>
 <div class="field form-group">
    <%= f.label :population %><br>
    <%= f.number_field :population, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", rows: "5" %>
  </div>
    <div class="field form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude, class: "form-control" %>
  </div>
   <div class="field form-group">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label "Photo" %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<% if notice != nil %>
  <p id="notice" class="alert alert-success" role="alert">
    <%= notice %>
  </p>
<% end %>
<h1>My Destination Wish List</h1>
<ul class="nav nav-pills" role="tablist">
  <li><%= link_to "All", destinations_path %></li>
  <% @my_countries.each do |c| %>
    <li><%= link_to "#{c.country}", controller: "destinations", country: "#{c.country}" %></li>
  <% end %>
</ul>
  <div class="row">
    <% @destinations.each do |destination| %>
      <div class="col-md-4">
       <div class="panel panel-default">
        <div class="panel-body">
          <h2><%= destination.city %></h2>
          <h3><%= destination.country.titleize %></h3>
          <% if destination.avatar_file_name != nil %>
   <%= image_tag destination.avatar.url(:medium), class: "img-responsive" %>
<% end %>
          <p>Population: <%= destination.population %></p>

         <div class="btn-group">
          <%= link_to 'Show', destination, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_destination_path(destination), class: "btn btn-default" %>
          <%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'New Destination', new_destination_path, class: "btn btn-primary" %>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
  <% if notice != nil %>
  <p id="notice" class="alert alert-success" role="alert">
    <%= notice %>
  </p>
<% end %>
<%= javascript_tag do %>
   latitude = '<%= j @destination.latitude.to_s %>';
   longitude = '<%= j @destination.longitude.to_s %>';
   address = '<%= j @destination.address %>';
   description = '<%= j @destination.description %>';
<% end %>
<h1><%= @destination.city %>, <%= @destination.country %></h1>
<%= image_tag @destination.avatar.url %>
<h2>Population <%= @destination.population %></h2>
 <h1><%= @destination.address %></h1>

 <p><%= @destination.latitude %>, <%= @destination.longitude %></p>

 <p><%= @destination.description %></p>

  <div id="destination-map"></div>


 <div class="btn-group">


  <%= link_to 'Edit', edit_destination_path(@destination), class: "btn btn-default" %>
  <%= link_to 'Back', destinations_path, class: "btn btn-default" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
    <link href="http://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Marck+Script' rel='stylesheet' type='text/css'>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
<%= link_to "Travel", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Destinations', destinations_path %>
</li>

        <li class="<%= 'active' if current_page? (about_path)%>"><%= link_to "About", about_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <div class="container">

<%= yield %>
</div>
 <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_api_key'] %>">
 </script>
</body>
</html>

app/views/mice/_form.html.erb
<%= form_for(@mouse) do |f| %>
  <% if @mouse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mouse.errors.count, "error") %> prohibited this mouse from being saved:</h2>

      <ul>
      <% @mouse.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mice/contact.html.erb
Hello

app/views/mice/edit.html.erb
<h1>Editing Mouse</h1>

<%= render 'form' %>

<%= link_to 'Show', @mouse %> |
<%= link_to 'Back', mice_path %>

app/views/mice/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mice</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mice.each do |mouse| %>
      <tr>
        <td><%= mouse.name %></td>
        <td><%= link_to 'Show', mouse %></td>
        <td><%= link_to 'Edit', edit_mouse_path(mouse) %></td>
        <td><%= link_to 'Destroy', mouse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mouse', new_mouse_path %>

app/views/mice/new.html.erb
<h1>New Mouse</h1>

<%= render 'form' %>

<%= link_to 'Back', mice_path %>

app/views/mice/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mouse.name %>
</p>

<%= link_to 'Edit', edit_mouse_path(@mouse) %> |
<%= link_to 'Back', mice_path %>

app/views/welcome/about.html.erb
<style>
  body {
    background: <%= @color %>;
  }
</style>
<h1>About me</h1>

<p>Lots of interesting stuffs.</p>
<p>My favorite color is <%= @color %></p>
<% if @size > 12 %>
  <p>My shoe size is <%= @size %>. I have HUGE feet.</p>
<% else %>
  <p>My shoe size is <%= @size %></p>
<% end %>

<%= link_to "Blue", about_path(color: "blue"), class: "btn btn-primary" %>
<%= link_to "Red", about_path(color: "red"), class: "btn btn-danger" %>

app/views/welcome/contact.html.erb
<h1>Contact Me</h1>
<p>Write me a note!</p>

app/views/welcome/index.html.erb
<h1>Welcome to my Travel Site</h1>
<p>This is my very awesome travel site.</p>
    <%= @homeland %>
<ul>
  <% @countries.each do |country| %>
    <li><%= country %></li>
  <% end %>
</ul>

<% @travel_pics.each do |pic| %>
<br>
  <%= image_tag pic, class: "img-responsive" %>
<% end %>

<table class="table">
  <tr>
    <% @united_states.each do |key,value| %>
    <th><%= key.titleize %></th>
    <% end %>
  </tr>
  <tr>
    <% @united_states.each do |key,value| %>
      <% if value.kind_of?(Array) %>
          <td><%= value.join(", ") %></td>
      <% else %>
         <td><%= value %></td>
      <% end %>
    <% end %>
  </tr>
</table>
<div id="map-canvas"></div>